{% set name = "pytest-helpers-namespace" %}
{% set version = "2021.4.29" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-helpers-namespace-{{ version }}.tar.gz
  sha256: 183524e3db4e2a1fea92e0ca3662a624ba44c9f3568da15679d7535ba6838a6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - pytest >=2.9.1
    - python >=2.7

test:
  imports:
    - pytest_helpers_namespace
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/saltstack/pytest-helpers-namespace
  summary: PyTest Helpers Namespace
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
